apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
  - hostname: console.apps.test.gcp.quaydev.org
    name: console
    namespace: openshift-console
  domain: apps.test.gcp.quaydev.org
