apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - github:
      clientID: 7160a496b1c9288ffd12
      clientSecret:
        name: github-secret
      organizations:
      - quay
    mappingMethod: claim
    name: github
    type: GitHub
