apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.14.5
    chart: jetstack/cert-manager
    helm:
      values: |
        installCRDs: true
  project: default
  syncPolicy:
    automated: {}
