apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.5.1
    chart: external-secrets
  project: default
  syncPolicy:
    automated: {}
