apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: openshift-gitops
spec:
  destination:
    namespace: kubernetes-replicator
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.mittwald.de'
    targetRevision: 2.9.1
    chart: kubernetes-replicator
  project: default
  syncPolicy:
    automated: {}
