apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: run-quay
spec:
  destination:
    namespace: run-quay
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dmage/run-quay.git'
    targetRevision: deploy
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
