apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: api-certs
  httpEmptyRequestsPolicy: Respond
  replicas: 2
