apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  nodePlacement:
    nodeSelector:
      quay-machineset: worker-a
  server:
    host: gitops.apps.test.gcp.quaydev.org
    route:
      enabled: true
      tls:
        termination: reencrypt
  rbac:
    policy: g, admins, role:admin
    scopes: '[groups]'
  resourceIgnoreDifferences:
    resourceIdentifiers:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      customization:
        jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      customization:
        jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      customization:
        jqPathExpressions:
        - '.spec.conversion.webhook.clientConfig.caBundle'
        - '.spec.conversion.webhook.clientConfig.service.name'
        - '.spec.conversion.webhook.clientConfig.service.namespace'
