apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  nodePlacement:
    nodeSelector:
      quay-machineset: worker-a
  server:
    host: gitops.apps.test.gcp.quaydev.org
    route:
      enabled: true
      tls:
        termination: reencrypt
  rbac:
    policy: g, admins, role:admin
    scopes: '[groups]'
  resourceCustomizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jqPathExpressions:
        - '.spec.conversion.webhook.clientConfig.caBundle'
        - '.spec.conversion.webhook.clientConfig.service.name'
        - '.spec.conversion.webhook.clientConfig.service.namespace'
