apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: clouddns-dns01-solver-svc-acct
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        key.json: '{{ .key | b64dec | toString }}'
  data:
  - secretKey: key
    remoteRef:
      key: test-cluster
      property: clouddns-dns01-solver-svc-acct/key
