apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: router-certs
    creationPolicy: Owner
    deletionPolicy: Delete
  template:
    type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: test-cluster
      property: router-certs/tls.crt
  - secretKey: tls.key
    remoteRef:
      key: test-cluster
      property: router-certs/tls.key
