apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-certs
  namespace: openshift-ingress
spec:
  secretName: router-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - quay
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
  - api.test.gcp.quaydev.org
  - "*.apps.test.gcp.quaydev.org"
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
