apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: router-certs
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ .crt | b64dec | toString }}'
        tls.key: '{{ .key | b64dec | toString }}'
  data:
  - secretKey: crt
    remoteRef:
      key: test-cluster
      property: router-certs/tls\.crt
  - secretKey: key
    remoteRef:
      key: test-cluster
      property: router-certs/tls\.key
