apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secret
  namespace: openshift-config
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: test-cluster
    kind: ClusterSecretStore
  target:
    name: github-secret
    creationPolicy: Owner
  data:
  - secretKey: clientSecret
    remoteRef:
      key: github-secret/clientSecret

