apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: github-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: clientSecret
    remoteRef:
      key: test-cluster
      property: github-secret/clientSecret
